spring.application.name=demologin

spring.datasource.url=jdbc:mysql://localhost:3310/login
spring.datasource.username=rtroncoso
spring.datasource.password=rtroncoso123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Desactivar creacion automatica de tablas con hibernante
spring.jpa.hibernate.ddl-auto=none

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration